deploy_name: nginx-deploy
pvc_name: my-pvc
namespace: homeworkhelm
replica: 3
app:
  label: nginx
  name: webserver
  image:
    repository: slvalt/nginx-custom
    tag: v1
  livenessProbeEnable: true
  livenessProbe:
    httpGet:
      path: /
      port: 8000
init:
  name: initcont
  image:
    repository: busybox
    tag: 1.28
nodeSelector:
  homework: "true"
  storage: "true"
url: http://homework.otus
sa: monitoring